#include <iostream>
#include "smart_array.hpp"

int main()
{
	SmartArray arr;
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	arr.pop_back();
	std::cout << "push_back 10" << std::endl;
	arr.push_back(10);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "push_back 40" << std::endl;
	arr.push_back(40);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "push_back 20" << std::endl;
	arr.push_back(20);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "push_back 30" << std::endl;
	arr.push_back(30);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "insert(2, 111)" << std::endl;
	arr.insert(2, 111);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "push_back 5" << std::endl;
	arr.push_back(5);
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "pop_back" << std::endl;
	arr.pop_back();
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "print arr[1]" << arr[1] << std::endl;
	std::cout << "print arr[3]" << arr[3] << std::endl;
	std::cout << "copy arr to arr2" << std::endl;
	SmartArray arr2(arr);
	std::cout << "print array arr2: ";
	print_array(arr2);
	std::cout << "resize(15)" << std::endl;
	arr.resize(15);
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "resize(20, 33)" << std::endl;
	arr.resize(20, 33);
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "erase(4)" << std::endl;
	arr.erase(4);
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "resize(5)" << std::endl;
	arr.resize(5);
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "assign(4, 15)" << std::endl;
	arr.assign(4, 15);
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "assign(1, 4, arr2)" << std::endl;
	arr.assign(1, 4, arr2);
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	std::cout << "assign({5, 4, 3, 2, 1})" << std::endl;
	arr.assign({5, 4, 3, 2, 1});
	std::cout << "print array: ";
	print_array(arr);
	std::cout << "capacity: " << arr.get_capacity() << std::endl;
	return 0;
}
